export enum RoutesEnums {
    INVESTOR_DETAILS="/investor-onboarding",
    REALTOR_DETAILS="/realtor-onboarding",
    START_UP ="/startup-onboarding",
    SYNIDCATE_DETAILS="/syndicate-onboarding",
    COMPLETE_DETAILS="/complete-details",
    COMPLETE_GOALS="/complete-goals",
    PHILOSOPHY_GOALS="/philosophy-goals",
    ADD_ATTACHMENTS="/add-attachments",
    SIGNUP="/signup",
    LOGIN="/login",
    VERIFICATION="/verification",
    WELCOME="/welcome",
    LINKEDIN="/linkedin",
    PRIVACY_POLICY="/privacy-policy",
    TERMS_CONDITIONS="/terms-and-conditions",
}