export enum RoutesEnums {
  FRONTEND_STATIC_LINK = "https://ambitious-hill-06b43d700.3.azurestaticapps.net",
  OVERVIEW = "/overview",
  INVESTOR_UPDATES = "/investor-updates",
  DATA_ROOMS = "/data-rooms",
  MARKET_INSIGHTS = "/market-insights",
  CONTACTS = "/contacts",
  CREATE_DEAL = "/create-deal",
  INVESTOR_DETAILS = "/investor-onboarding",
  PROPERTY_OWNER_DETAILS = "/property-owner-onboarding",
  FUNDRAISER_DETAILS = "/fundraiser-onboarding",
  SYNIDCATE_DETAILS = "/syndicate-onboarding",
  COMPLETE_DETAILS = "/complete-details",
  COMPLETE_GOALS = "/complete-goals",
  PHILOSOPHY_GOALS = "/philosophy-goals",
  ADD_ATTACHMENTS = "/add-attachments",
  SIGNUP = "/signup",
  LOGIN = "/login",
  VERIFICATION = "/verification",
  WELCOME = "/welcome",
  LINKEDIN = "/linkedin",
  PRIVACY_POLICY = "/privacy-policy",
  TERMS_CONDITIONS = "/terms-and-conditions",
  FUNDRAISER_DASHBOARD = "/fundraiser",
  PROPERTY_OWNER_DASHBOARD = "/property-owner",
  INVESTOR_DASHBOARD = "/investor",
  INVESTOR_SYNDICATES = "/investor-syndicates",
  INVESTOR_DEALS = "/investors-deals",
  SYNDICATE_DETAILED_VIEW = "/syndicate-detailed-view",
  SYNDICATE_DASHBOARD = "/syndicate",
  DEAL_APPROVAL = "/deal-approval",
  STARTUP_INVESTMENTS = "/startup-investments",
  DEAL_DETAIL = "/view-deal",
  SYNDICATE_DEAL_DETAIL = "/deal",
  DEAL_SYNDICATE_REQUESTS = "/deal-syndicate-requests",
  SYNDICATES_ALL = "/syndicates-all",
  SYNDICATE_INVESTMENTS = "/syndicate-investments",
  SYNDICATE_MANAGE_GROUP = "/manage-group",
  GUEST_DEAL_VIEW = "/deal-guest-view",
  PROFILE = "/profile",
  INVESTOR_DEAL_DETAILS = "/investor-deal-details",
  LOADING_LOGOUT = "/logging-out",
  WALLET = "/wallet"
}

export enum StartupRoutes {}
