export enum RoutesEnums {
    INVESTOR_DETAILS="/investor-type",
    REALTOR_DETAILS="/realtor-type",
    START_UP ="/startup-type",
    SYNIDCATE_DETAILS="/syndicate-lead",
    COMPLETE_DETAILS="/complete-details",
    COMPLETE_GOALS="/complete-goals",
    PHILOSOPHY_GOALS="/philosophy-goals",
    ADD_ATTACHMENTS="/add-attachments",
    SIGNUP="/signup",
    LOGIN="/login",
    VERIFICATION="/verification",
    WELCOME="/welcome",
    LINKEDIN="/linkedin",
    PRIVACY_POLICY="/privacy-policy",
    TERMS_CONDITIONS="/terms-and-conditions",
}